//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a mano.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.controls
{
    public partial class ValidarModificacionProducto
    {
        protected global::System.Web.UI.WebControls.TextBox txtCodigo;

        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDescripcion;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revDescripcion;

        protected global::System.Web.UI.WebControls.DropDownList ddlCategoria;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCategoria;

        protected global::System.Web.UI.WebControls.DropDownList ddlMarca;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvMarca;

        protected global::System.Web.UI.WebControls.DropDownList ddlIVA;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIVA;

        protected global::System.Web.UI.WebControls.TextBox txtCantidad;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCantidad;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCantidad;

        protected global::System.Web.UI.WebControls.TextBox txtPrecio;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPrecio;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPrecio;

        protected global::System.Web.UI.WebControls.FileUpload fuImagen;

        protected global::System.Web.UI.WebControls.Image imgProducto;
    }
}
